server:
  port: 9000
  servlet:
    application-display-name: servicio-credits

datasource:
  url: mongodb://localhost:18200/dbcredits
  
eureka:
  client:
    serviceUrl.defaultZone: http://localhost:8761/eureka